### ISSUE TITLE
Rewrite `build` and `merge` scripts to use `metadata.json` instead of `metadata.desktop`

### ISSUE THREAD

**Issue by stepanzubkov** [Zren/plasma-applet-lib#3]
Now translation scripts use `metadata.desktop`, but it is deprecated. It's recommended to use `metadata.json` file for metadata storing.

**Comment by Zren** [comment]
The `gettext` commands support parsing and updating `.desktop` files, but they don't support the KDE `metadata.json` format. The KDE SysAdmin's probably have a custom script to parse those messages for their Ki18n translations, but I don't know if that code can be used standalone.

A while ago I started writing a huge python file which combined `./build`, `./package/translate/build`, and `./package/translate/merge` into a single file. It supported parsing both `.desktop` and `.json`. However I stopped working on it once I realized I would need to keep a `.desktop` file to translate the `Name` and `Comment`/`Description`. After I noticed that, I just planned to use the `desktoptojson` script when building the zipped `.plasmoid`.

* https://gist.github.com/Zren/c933d4ae1b3549b2a6df97ff9cfdcd3b
* https://gist.github.com/Zren/c933d4ae1b3549b2a6df97ff9cfdcd3b#file-kpac-py-L71

Edit: Even you don't care about translating the Name/Description in `metadata.json`, parsing `json` in bash is a pain (which is why I needed to do a rewrite). It's much simpler with `kreadconfig5` and `.desktop`.
